pulse.rules = [
    {
        matches = [
            {
                application.process.binary = "wine64-preloader"
            },
            {
                application.process.binary = "wine-preloader"
            },
            {
                application.name = "THE FINALS"
            }
        ]
        actions = {
            quirks = [ remove-capture-dont-move ]
            update-props = {
                node.dont-reconnect = false
            }
        }
    },
    {
        matches = [
            {
                application.name = "THE FINALS"
                media.name = "~.*#1.*"
            }
        ]
        actions = {
            update-props = {
                node.description = "THE FINALS (Game Audio)"
            }
        }
    },
    {
        matches = [
            {
                application.name = "THE FINALS"
                media.name = "~.*#2.*"
            }
        ]
        actions = {
            update-props = {
                node.description = "THE FINALS (Voice Chat)"
            }
        }
    },
    {
        matches = [
            {
                application.name = "THE FINALS"
                media.name = "~.*#6.*"
            }
        ]
        actions = {
            update-props = {
                node.description = "THE FINALS (Music & UI)"
            }
        }
    },
    {
        matches = [
            {
                application.name = "THE FINALS"
                media.name = "~.*#5.*"
            }
        ]
        actions = {
            update-props = {
                node.description = "THE FINALS (Microphone)"
            }
        }
    }
]
