--ozone-platform-hint=auto
--enable-features=TouchpadOverscrollHistoryNavigation,WaylandWindowDecorations,VaapiVideoDecodeLinuxGL,VaapiIgnoreDriverChecks,CanvasOopRasterization
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--canvas-oop-rasterization
--enable-wayland-ime
--smooth-scrolling
